### ISSUE TITLE
xxx_avg is average cycles, so the smaller the proportion, the performance is better. right ?

### ISSUE THREAD

**Issue by tqolf** [moon-chilled/fancy-memset#1]

**Comment by moon-chilled** [comment]
Lower number of cycles is better, but note the proportion is inverted in the printout; a higher proportion is a case where fancy memset did better.  I recognise that this is not the most intuitive thing :P

Note the whole benchmark is kind of suspect; it doesn't use different sizes in sequence (testing the supposedly superior branch pred), nor does it use memory not already in cache (in which case I expect rep movs and bionic to do better, as they do non-temporal writes).  I have been meaning to write some instrumentations so I can optimize for (and better gauge) real application behaviour, but haven't got around to it yet.
